server:
  port: 8189

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: postgresql

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true

